# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aquaskk = {
    pname = "aquaskk";
    version = "4.7.8";
    src = fetchurl {
      url = "https://github.com/codefirst/aquaskk/releases/download/4.7.8/AquaSKK-4.7.8.pkg";
      sha256 = "sha256-4MKHJP9utaAflVhaJdJaCMQpamV8o1kO4Uz9lzGN+V4=";
    };
  };
  bizin-gothic-nf = {
    pname = "bizin-gothic-nf";
    version = "0.0.4";
    src = fetchurl {
      url = "https://github.com/yuru7/bizin-gothic/releases/download/v0.0.4/BizinGothicNF_v0.0.4.zip";
      sha256 = "sha256-AnmCv71TXUEfA/e/YDVFSTUW61Gpi0lhYFPpJrkhEhU=";
    };
  };
  claude-code-ide = {
    pname = "claude-code-ide";
    version = "32d853e20b9d245a6ee89c4a153a4e568250c62c";
    src = fetchFromGitHub {
      owner = "manzaltu";
      repo = "claude-code-ide.el";
      rev = "32d853e20b9d245a6ee89c4a153a4e568250c62c";
      fetchSubmodules = false;
      sha256 = "sha256-OrcnUZXqRijJCgf1QE5kkPKKdWSJ4oMYt47Sn/EdQy0=";
    };
    date = "2025-09-15";
  };
  cskk = {
    pname = "cskk";
    version = "d121500a10afb9d1fb703fa8b47c13ab1bb233da";
    src = fetchFromGitHub {
      owner = "naokiri";
      repo = "cskk";
      rev = "d121500a10afb9d1fb703fa8b47c13ab1bb233da";
      fetchSubmodules = false;
      sha256 = "sha256-Iv3DFjYUiGzoYyH/r69LUEgLh7RCQS/oKL0rttvW+fU=";
    };
    date = "2025-10-13";
  };
  fcitx5-cskk = {
    pname = "fcitx5-cskk";
    version = "7ea513375d5412b37ab0251476f792d2467547e5";
    src = fetchFromGitHub {
      owner = "fcitx";
      repo = "fcitx5-cskk";
      rev = "7ea513375d5412b37ab0251476f792d2467547e5";
      fetchSubmodules = false;
      sha256 = "sha256-ooAfyoHpFoMiF0ZpvasW72Xk5BZ/t3qEGxRX8keWFuA=";
    };
    date = "2025-11-07";
  };
  gcal = {
    pname = "gcal";
    version = "7b4fc16906850c7be7100d6e239c183ed9a054e4";
    src = fetchFromGitHub {
      owner = "misohena";
      repo = "gcal";
      rev = "7b4fc16906850c7be7100d6e239c183ed9a054e4";
      fetchSubmodules = false;
      sha256 = "sha256-jU4dwlJaGjufbmOzTe7V/5Av2WuOZGMc49VmeX7yh8Y=";
    };
    date = "2024-06-19";
  };
  lean4-mode = {
    pname = "lean4-mode";
    version = "1388f9d1429e38a39ab913c6daae55f6ce799479";
    src = fetchFromGitHub {
      owner = "leanprover-community";
      repo = "lean4-mode";
      rev = "1388f9d1429e38a39ab913c6daae55f6ce799479";
      fetchSubmodules = false;
      sha256 = "sha256-6XFcyqSTx1CwNWqQvIc25cuQMwh3YXnbgr5cDiOCxBk=";
    };
    date = "2025-05-31";
  };
  niri-taskbar = {
    pname = "niri-taskbar";
    version = "v0.3.0+niri.25.08";
    src = fetchFromGitHub {
      owner = "LawnGnome";
      repo = "niri-taskbar";
      rev = "v0.3.0+niri.25.08";
      fetchSubmodules = false;
      sha256 = "sha256-Gbzh4OTkvtP9F/bfDUyA14NH2DMDdr3i6oFoFwinEAg=";
    };
  };
  nx-rbw = {
    pname = "nx-rbw";
    version = "553d0f9d041b93d9600b424ae77cf3e2d6d096ae";
    src = fetchurl {
      url = "https://codeberg.org/ablatedsprocket/nx-rbw/archive/main.tar.gz";
      sha256 = "sha256-zkcT9hM2JSHhYfJSLldYKg31BLHto3rbfhHGZZvkfAk=";
    };
    date = "2024-07-15";
  };
  nx-zotero = {
    pname = "nx-zotero";
    version = "4a6b0ff72ae829b1789c1e21ce6c072b8af22da2";
    src = fetchFromGitHub {
      owner = "rolling-robot";
      repo = "nx-zotero";
      rev = "4a6b0ff72ae829b1789c1e21ce6c072b8af22da2";
      fetchSubmodules = false;
      sha256 = "sha256-YvCJcvy7rmXOJ5eLgHE9DtvugwYrYKpjIoXl57TMXk4=";
    };
    date = "2024-05-11";
  };
  ol-emacs-slack = {
    pname = "ol-emacs-slack";
    version = "299bd86280179999b049abc7252eb1bffa8a5ddd";
    src = fetchFromGitHub {
      owner = "ag91";
      repo = "ol-emacs-slack";
      rev = "299bd86280179999b049abc7252eb1bffa8a5ddd";
      fetchSubmodules = false;
      sha256 = "sha256-uEVJYAqVolyL8Li7zagl/4XcgkNJH+JIupLsh7tJhEE=";
    };
    date = "2024-09-17";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "9973bd3b91e4733a3edd1fca232208c837c05473";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "9973bd3b91e4733a3edd1fca232208c837c05473";
      fetchSubmodules = false;
      sha256 = "sha256-st3338Jk9kZ5BLEPRJZhjqdncMpLoWNwp60ZwKEObyU=";
    };
    date = "2025-04-12";
  };
  org-roam-review = {
    pname = "org-roam-review";
    version = "d142559096b3e3ee288d439c59fa6a30abe1b11f";
    src = fetchFromGitHub {
      owner = "chrisbarrett";
      repo = "nursery";
      rev = "d142559096b3e3ee288d439c59fa6a30abe1b11f";
      fetchSubmodules = false;
      sha256 = "sha256-oGrflni+XsbENNpyahqqX/Wu+Uenc1/zxLsivPZ5SSM=";
    };
    date = "2025-02-15";
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.6.1";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.6.1/qutebrowser-3.6.1-arm64.dmg";
      sha256 = "sha256-2jk1nSq2O7z6tsVX7/ypvu2ipQh1mb8/Dz/n9KnqvAM=";
    };
  };
  typst-preview = {
    pname = "typst-preview";
    version = "c685857f2d61133fc268509b39796b2718728f29";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "c685857f2d61133fc268509b39796b2718728f29";
      fetchSubmodules = false;
      sha256 = "sha256-+426otCa0TASEo9Z+2yH8SUJIGtGEdl35/BdmfBBDbA=";
    };
    date = "2025-11-10";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.7.3851.54";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.7.3851.54.universal.dmg";
      sha256 = "sha256-eHwfO/uDV35LmZAYXMtf7fh7ZxSNBrnqPSFHNWxYMlA=";
    };
  };
}
