# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aquaskk = {
    pname = "aquaskk";
    version = "4.7.7";
    src = fetchurl {
      url = "https://github.com/codefirst/aquaskk/releases/download/4.7.7/AquaSKK-4.7.7.pkg";
      sha256 = "sha256-UwqZR5YG/7Ih0BHpna/YUch+Ovs/rOJoVCmB04UYwBo=";
    };
  };
  bizin-gothic-nf = {
    pname = "bizin-gothic-nf";
    version = "0.0.4";
    src = fetchurl {
      url = "https://github.com/yuru7/bizin-gothic/releases/download/v0.0.4/BizinGothicNF_v0.0.4.zip";
      sha256 = "sha256-AnmCv71TXUEfA/e/YDVFSTUW61Gpi0lhYFPpJrkhEhU=";
    };
  };
  claude-code-ide = {
    pname = "claude-code-ide";
    version = "76d83f30fd39b8d4b16b7f2b185e1e3f74cab227";
    src = fetchFromGitHub {
      owner = "manzaltu";
      repo = "claude-code-ide.el";
      rev = "76d83f30fd39b8d4b16b7f2b185e1e3f74cab227";
      fetchSubmodules = false;
      sha256 = "sha256-9qj9BEkaB/AFRzNavdaYsdnW3w2ZRMW1o+q9hjPL8D0=";
    };
    date = "2025-08-25";
  };
  cskk = {
    pname = "cskk";
    version = "24803d65761d4ac2f13bf564f2a7c73a343b34e1";
    src = fetchFromGitHub {
      owner = "naokiri";
      repo = "cskk";
      rev = "24803d65761d4ac2f13bf564f2a7c73a343b34e1";
      fetchSubmodules = false;
      sha256 = "sha256-lhLNtSmD5XiG0U6TLWgN+YA/f7UJ/RyHoe5vq5OopuI=";
    };
    date = "2025-04-26";
  };
  fcitx5-cskk = {
    pname = "fcitx5-cskk";
    version = "6d4407c64df46423c378afeefa71bda3282a7cec";
    src = fetchFromGitHub {
      owner = "fcitx";
      repo = "fcitx5-cskk";
      rev = "6d4407c64df46423c378afeefa71bda3282a7cec";
      fetchSubmodules = false;
      sha256 = "sha256-UfEmRenWiX2xbIirkDRbix1YQrDz1/sVg6yut8ZRJ0k=";
    };
    date = "2025-04-22";
  };
  gcal = {
    pname = "gcal";
    version = "7b4fc16906850c7be7100d6e239c183ed9a054e4";
    src = fetchFromGitHub {
      owner = "misohena";
      repo = "gcal";
      rev = "7b4fc16906850c7be7100d6e239c183ed9a054e4";
      fetchSubmodules = false;
      sha256 = "sha256-jU4dwlJaGjufbmOzTe7V/5Av2WuOZGMc49VmeX7yh8Y=";
    };
    date = "2024-06-19";
  };
  niri-taskbar = {
    pname = "niri-taskbar";
    version = "v0.2.0+niri.25.05";
    src = fetchFromGitHub {
      owner = "LawnGnome";
      repo = "niri-taskbar";
      rev = "v0.2.0+niri.25.05";
      fetchSubmodules = false;
      sha256 = "sha256-2DemaNMzdUjziRvDah4ZvYsyu44+EuSe2w55t21hPws=";
    };
  };
  nx-rbw = {
    pname = "nx-rbw";
    version = "553d0f9d041b93d9600b424ae77cf3e2d6d096ae";
    src = fetchurl {
      url = "https://codeberg.org/ablatedsprocket/nx-rbw/archive/main.tar.gz";
      sha256 = "sha256-zkcT9hM2JSHhYfJSLldYKg31BLHto3rbfhHGZZvkfAk=";
    };
    date = "2024-07-15";
  };
  nx-zotero = {
    pname = "nx-zotero";
    version = "4a6b0ff72ae829b1789c1e21ce6c072b8af22da2";
    src = fetchFromGitHub {
      owner = "rolling-robot";
      repo = "nx-zotero";
      rev = "4a6b0ff72ae829b1789c1e21ce6c072b8af22da2";
      fetchSubmodules = false;
      sha256 = "sha256-YvCJcvy7rmXOJ5eLgHE9DtvugwYrYKpjIoXl57TMXk4=";
    };
    date = "2024-05-11";
  };
  ol-emacs-slack = {
    pname = "ol-emacs-slack";
    version = "299bd86280179999b049abc7252eb1bffa8a5ddd";
    src = fetchFromGitHub {
      owner = "ag91";
      repo = "ol-emacs-slack";
      rev = "299bd86280179999b049abc7252eb1bffa8a5ddd";
      fetchSubmodules = false;
      sha256 = "sha256-uEVJYAqVolyL8Li7zagl/4XcgkNJH+JIupLsh7tJhEE=";
    };
    date = "2024-09-17";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "9973bd3b91e4733a3edd1fca232208c837c05473";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "9973bd3b91e4733a3edd1fca232208c837c05473";
      fetchSubmodules = false;
      sha256 = "sha256-st3338Jk9kZ5BLEPRJZhjqdncMpLoWNwp60ZwKEObyU=";
    };
    date = "2025-04-12";
  };
  org-roam-review = {
    pname = "org-roam-review";
    version = "d142559096b3e3ee288d439c59fa6a30abe1b11f";
    src = fetchFromGitHub {
      owner = "chrisbarrett";
      repo = "nursery";
      rev = "d142559096b3e3ee288d439c59fa6a30abe1b11f";
      fetchSubmodules = false;
      sha256 = "sha256-oGrflni+XsbENNpyahqqX/Wu+Uenc1/zxLsivPZ5SSM=";
    };
    date = "2025-02-15";
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.5.1";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.5.1/qutebrowser-3.5.1-arm64.dmg";
      sha256 = "sha256-sUB4ECoMn6jSFJD4+QLY7khrn7PgOMUrUPQvca88Gxo=";
    };
  };
  typst-preview = {
    pname = "typst-preview";
    version = "4f3decb8d9b85b1a06b0dfbd0fccaa0d2d2c24b4";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "4f3decb8d9b85b1a06b0dfbd0fccaa0d2d2c24b4";
      fetchSubmodules = false;
      sha256 = "sha256-rxXgIoILnxyn543keCkpuv80TLaSATN1T7hCvnM8inU=";
    };
    date = "2025-08-12";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.5.3735.64";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.5.3735.64.universal.dmg";
      sha256 = "sha256-E+ICYBGEvyAMkH22I9gaMgX/+D7B27igZBZ6GYXxz8A=";
    };
  };
}
