# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aquaskk = {
    pname = "aquaskk";
    version = "4.7.8";
    src = fetchurl {
      url = "https://github.com/codefirst/aquaskk/releases/download/4.7.8/AquaSKK-4.7.8.pkg";
      sha256 = "sha256-4MKHJP9utaAflVhaJdJaCMQpamV8o1kO4Uz9lzGN+V4=";
    };
  };
  bizin-gothic-nf = {
    pname = "bizin-gothic-nf";
    version = "0.0.4";
    src = fetchurl {
      url = "https://github.com/yuru7/bizin-gothic/releases/download/v0.0.4/BizinGothicNF_v0.0.4.zip";
      sha256 = "sha256-AnmCv71TXUEfA/e/YDVFSTUW61Gpi0lhYFPpJrkhEhU=";
    };
  };
  claude-code-ide = {
    pname = "claude-code-ide";
    version = "a5494523dc8c3031375aa53d6321abfd9bc7288b";
    src = fetchFromGitHub {
      owner = "manzaltu";
      repo = "claude-code-ide.el";
      rev = "a5494523dc8c3031375aa53d6321abfd9bc7288b";
      fetchSubmodules = false;
      sha256 = "sha256-Mw5MNx4RMk+2oXcjIVclel1jis1jHTj8S3uqTDYN4KQ=";
    };
    date = "2026-02-01";
  };
  cskk = {
    pname = "cskk";
    version = "bbe34fcde4c314f9e9bb975d0806885ead1b8d8d";
    src = fetchFromGitHub {
      owner = "naokiri";
      repo = "cskk";
      rev = "bbe34fcde4c314f9e9bb975d0806885ead1b8d8d";
      fetchSubmodules = false;
      sha256 = "sha256-olQ0ru5JPx3F0nL+EVR5rmR7nAfceUPSzaATRACJUJU=";
    };
    date = "2026-01-04";
  };
  fcitx5-cskk = {
    pname = "fcitx5-cskk";
    version = "da7e2ce7d8f1319368adae3d9e96513058c40018";
    src = fetchFromGitHub {
      owner = "fcitx";
      repo = "fcitx5-cskk";
      rev = "da7e2ce7d8f1319368adae3d9e96513058c40018";
      fetchSubmodules = false;
      sha256 = "sha256-qJ3UQphoHOSa4wYowR6wQp+RakovoQVzuii4DAWUWuY=";
    };
    date = "2026-01-12";
  };
  gcal = {
    pname = "gcal";
    version = "7b4fc16906850c7be7100d6e239c183ed9a054e4";
    src = fetchFromGitHub {
      owner = "misohena";
      repo = "gcal";
      rev = "7b4fc16906850c7be7100d6e239c183ed9a054e4";
      fetchSubmodules = false;
      sha256 = "sha256-jU4dwlJaGjufbmOzTe7V/5Av2WuOZGMc49VmeX7yh8Y=";
    };
    date = "2024-06-19";
  };
  lean4-mode = {
    pname = "lean4-mode";
    version = "1388f9d1429e38a39ab913c6daae55f6ce799479";
    src = fetchFromGitHub {
      owner = "leanprover-community";
      repo = "lean4-mode";
      rev = "1388f9d1429e38a39ab913c6daae55f6ce799479";
      fetchSubmodules = false;
      sha256 = "sha256-6XFcyqSTx1CwNWqQvIc25cuQMwh3YXnbgr5cDiOCxBk=";
    };
    date = "2025-05-31";
  };
  niri-taskbar = {
    pname = "niri-taskbar";
    version = "v0.4.0+niri.25.11";
    src = fetchFromGitHub {
      owner = "LawnGnome";
      repo = "niri-taskbar";
      rev = "v0.4.0+niri.25.11";
      fetchSubmodules = false;
      sha256 = "sha256-aE5v94AA6bC0CP8pv/SPBxGKpkH+GxR/p7hTKXlvk3E=";
    };
  };
  nx-rbw = {
    pname = "nx-rbw";
    version = "553d0f9d041b93d9600b424ae77cf3e2d6d096ae";
    src = fetchurl {
      url = "https://codeberg.org/ablatedsprocket/nx-rbw/archive/main.tar.gz";
      sha256 = "sha256-zkcT9hM2JSHhYfJSLldYKg31BLHto3rbfhHGZZvkfAk=";
    };
    date = "2024-07-15";
  };
  nx-zotero = {
    pname = "nx-zotero";
    version = "4a6b0ff72ae829b1789c1e21ce6c072b8af22da2";
    src = fetchFromGitHub {
      owner = "rolling-robot";
      repo = "nx-zotero";
      rev = "4a6b0ff72ae829b1789c1e21ce6c072b8af22da2";
      fetchSubmodules = false;
      sha256 = "sha256-YvCJcvy7rmXOJ5eLgHE9DtvugwYrYKpjIoXl57TMXk4=";
    };
    date = "2024-05-11";
  };
  ol-emacs-slack = {
    pname = "ol-emacs-slack";
    version = "93ecc9d5fbe94f1693a4aa0226a09f35b55d9acd";
    src = fetchFromGitHub {
      owner = "ag91";
      repo = "ol-emacs-slack";
      rev = "93ecc9d5fbe94f1693a4aa0226a09f35b55d9acd";
      fetchSubmodules = false;
      sha256 = "sha256-mnDlzuGsjETrUMvor9p5nN2qdYXSawVZOB/lL8Lnh+8=";
    };
    date = "2026-01-22";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
      fetchSubmodules = false;
      sha256 = "sha256-+q7KmbU8A+uR61BSa528vYbdFSj2WGsFWYW/5q7J9Kw=";
    };
    date = "2026-01-02";
  };
  org-roam-review = {
    pname = "org-roam-review";
    version = "d142559096b3e3ee288d439c59fa6a30abe1b11f";
    src = fetchFromGitHub {
      owner = "chrisbarrett";
      repo = "nursery";
      rev = "d142559096b3e3ee288d439c59fa6a30abe1b11f";
      fetchSubmodules = false;
      sha256 = "sha256-oGrflni+XsbENNpyahqqX/Wu+Uenc1/zxLsivPZ5SSM=";
    };
    date = "2025-02-15";
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.6.3";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.6.3/qutebrowser-3.6.3-arm64.dmg";
      sha256 = "sha256-Kk+uWs2QJouaD9U5ma3AJsR4HtqW/Blh8zM9Faj1u00=";
    };
  };
  typst-preview = {
    pname = "typst-preview";
    version = "c685857f2d61133fc268509b39796b2718728f29";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "c685857f2d61133fc268509b39796b2718728f29";
      fetchSubmodules = false;
      sha256 = "sha256-+426otCa0TASEo9Z+2yH8SUJIGtGEdl35/BdmfBBDbA=";
    };
    date = "2025-11-10";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.8.3925.56";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.8.3925.56.universal.dmg";
      sha256 = "sha256-XfDH1VokGIQwQeuszfA1AXUe5CR94eLnUpkESqiwbsw=";
    };
  };
}
